[package]
authors = ["MikiAlex <miikiialexx@gmail.com>"]
edition = "2021"
name = "rendiation-content-virtualization"
version = "0.1.0"

[dependencies]
fast-hash-collection = { path = "../../utility/fast-hash-collection" }
query = { path = "../../utility/query" }
futures = { workspace = true, features = ["thread-pool"] }
rendiation-shader-api = { path = "../../shader/api" }
rendiation-webgpu = { path = "../../platform/graphics/webgpu" }

rendiation-texture-gpu-system = { path = "../texture/gpu-system" }

[lints]
workspace = true
