[package]
authors = ["mikialex <miikiialexx@gmail.com>"]
edition = "2021"
name = "rendiation-fast-down-sampling-2d"
version = "0.1.0"

[dependencies]
rendiation-shader-api = { path = "../api" }
rendiation-webgpu = { path = "../../platform/graphics/webgpu" }

pollster = { workspace = true } # used in examples

[lints]
workspace = true
