[package]
edition = "2021"
name = "reactive-query"
version = "0.0.1"

[dependencies]
query = { path = "../query" }
fast-hash-collection = { path = "../fast-hash-collection" }
futures = { workspace = true }
pin-project = { workspace = true }
heap-tools = { path = "../heap-tools" }
storage = { path = "../storage" }
smallvec = { workspace = true }
tracing = { workspace = true }
dashmap = { workspace = true }
dyn-clone = { workspace = true }
xalloc = "0.2.7"
reactive-stream = { path = "../reactive-stream" }
parking_lot = { workspace = true }

[lints]
workspace = true
