[package]
authors = ["mikialex <miikiialexx@gmail.com>"]
edition = "2021"
name = "rendiation-infinity-primitive"
version = "0.1.0"

[dependencies]
rendiation-algebra = { path = "../../math/algebra" }
rendiation-scene-core = { path = "../../scene/core" }
rendiation-scene-rendering-gpu-base = { path = "../../scene/rendering/gpu-base" }
rendiation-shader-api = { path = "../../shader/api" }
database = { path = "../../utility/database" }
rendiation-webgpu = { path = "../../platform/graphics/webgpu" }
rendiation-shader-library = { path = "../../shader/library" }

[lints]
workspace = true
