[package]
authors = ["mikialex <miikiialexx@gmail.com>"]
edition = "2021"
name = "rendiation-texture-loader"
version = "0.1.0"

[dependencies]
image = { workspace = true }
rendiation-algebra = { path = "../../../math/algebra" }
rendiation-texture-core = { path = "../core" }
thiserror = { workspace = true }

[lints]
workspace = true
