[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-mesh-lod-graph-rendering"
version = "0.1.0"

[dependencies]
fast-hash-collection = { path = "../../../utility/fast-hash-collection" }
database = { path = "../../../utility/database" }
log = { workspace = true }
rendiation-algebra = { path = "../../../math/algebra" }
rendiation-geometry = { path = "../../../math/geometry" }
rendiation-scene-core = { path = "../../core" }
rendiation-scene-rendering-gpu-base = { path = "../../rendering/gpu-base" }
rendiation-shader-api = { path = "../../../shader/api" }
rendiation-device-parallel-compute = { path = "../../../shader/parallel-compute" }
rendiation-webgpu-reactive-utils = { path = "../../../platform/graphics/webgpu-reactive-utils" }
reactive = { path = "../../../utility/reactive" }
rendiation-webgpu = { path = "../../../platform/graphics/webgpu" }
rendiation-mesh-lod-graph = { path = "../../../content/mesh/lod-graph" }

[lints]
workspace = true
