[package]
edition = "2021"
name = "rendiation-algebra"
version = "1.0.0"

[dependencies]
bytemuck = { workspace = true, features = ["derive"] }
num-traits = "0.2"
dyn-clone = { workspace = true }
paste = { workspace = true }
facet = { workspace = true }
serde = { workspace = true }


[dev-dependencies]
cgmath = "0.18.0"

[lints]
workspace = true
