[package]
edition = "2021"
name = "rendiation-algebra"
version = "0.1.0"

[dependencies]
bytemuck = { workspace = true, features = ["derive"] }
num-traits = "0.2"
paste = { workspace = true }
serde = { version = "1.0.215", features = ["serde_derive"] }
serde_derive = "1.0.215"


[dev-dependencies]
cgmath = "0.18.0"

[lints]
workspace = true
