[package]
edition = "2021"
name = "event-source"
version = "0.0.1"

[dependencies]
parking_lot = { workspace = true }
futures = { workspace = true }
pin-project = { workspace = true }
slab = "0.4.11"
storage = { path = "../storage" }


[lints]
workspace = true
