[package]
edition = "2021"
name = "rendiation-scene-gltf-loader"
version = "0.0.1"

[dependencies]
bytemuck = { workspace = true }
fast-hash-collection = { path = "../../../../utility/fast-hash-collection" }
gltf = { version = "1.2.0", features = [
    "KHR_materials_pbrSpecularGlossiness",
    "KHR_lights_punctual",
    "KHR_materials_unlit",
] }
half = { version = "2.6" }
database = { path = "../../../../utility/database" }
rendiation-algebra = { path = "../../../../math/algebra" }
rendiation-geometry = { path = "../../../../math/geometry" }
rendiation-mesh-core = { path = "../../../../content/mesh/core" }
rendiation-scene-core = { path = "../../../core" }
rendiation-shader-api = { path = "../../../../shader/api" }
rendiation-texture-core = { path = "../../../../content/texture/core" }

[lints]
workspace = true
