[package]
edition = "2021"
name = "rendiation-geometry"
version = "0.1.0"

[dependencies]
bytemuck = { workspace = true, features = ["derive"] }
rendiation-algebra = { path = "../algebra" }
facet = { workspace = true }

[lints]
workspace = true
