[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-lighting-gi-ddgi"
version = "0.1.0"

[dependencies]
rendiation-webgpu = { path = "../../../../platform/graphics/webgpu" }
rendiation-algebra = { path = "../../../../math/algebra" }
rendiation-geometry = { path = "../../../../math/geometry" }
rendiation-shader-api = { path = "../../../../shader/api" }
rendiation-shader-library = { path = "../../../../shader/library" }
rendiation-lighting-transport = { path = "../../transport" }
rendiation-lighting-gpu-system = { path = "../../gpu-system/lighting-system" }


[lints]
workspace = true
