[package]
authors = ["MikiAlex <miikiialexx@gmail.com>"]
edition = "2021"
name = "rendiation-texture-types"
version = "0.1.0"

[dependencies]
serde = { workspace = true }
facet = { workspace = true }

[lints]
workspace = true
