[package]
authors = ["MikiAlex <miikiialexx@gmail.com>"]
edition = "2021"
name = "rendiation-lighting-gpu-system"
version = "0.1.0"

[dependencies]
rendiation-algebra = { path = "../../../../math/algebra" }
rendiation-shader-api = { path = "../../../../shader/api" }
rendiation-webgpu = { path = "../../../../platform/graphics/webgpu" }
rendiation-lighting-transport = { path = "../../transport" }
rendiation-lighting-punctual = { path = "../../punctual" }
rendiation-lighting-shadow-map = { path = "../shadow-map" }


[lints]
workspace = true
