[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-lighting-shadow-map"
version = "0.1.0"

[dependencies]
fast-hash-collection = { path = "../../../../utility/fast-hash-collection" }
parking_lot = { workspace = true }
database = { path = "../../../../utility/database" }
rendiation-algebra = { path = "../../../../math/algebra" }
rendiation-shader-api = { path = "../../../../shader/api" }
rendiation-shader-library = { path = "../../../../shader/library" }
rendiation-texture-core = { path = "../../../texture/core" }
rendiation-texture-packer = { path = "../../../texture/packer" }

reactive = { path = "../../../../utility/reactive" }
rendiation-webgpu = { path = "../../../../platform/graphics/webgpu" }
rendiation-webgpu-reactive-utils = { path = "../../../../platform/graphics/webgpu-reactive-utils" }

[lints]
workspace = true
