[alias]
xtask = "run -p rendiation-xtask --"

# Needed until https://github.com/rust-random/getrandom/issues/675 is resolved.
[target.wasm32-unknown-unknown]
rustflags = ["--cfg", "getrandom_backend=\"wasm_js\""]
