[package]
authors = ["mikialex <miikiialexx@gmail.com>"]
edition = "2021"
name = "rendiation-color"
version = "0.1.0"

[dependencies]
bytemuck = { workspace = true }
rendiation-algebra = { path = "../../math/algebra" }

[lints]
workspace = true
