[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-lighting-ltc"
version = "0.1.0"

[dependencies]
rendiation-algebra = { path = "../../../math/algebra" }
rendiation-shader-api = { path = "../../../shader/api" }
rendiation-texture-core = { path = "../../texture/core" }

[dev-dependencies]
rendiation-texture-loader = { path = "../../texture/loader" }
image = "*"

[lints]
workspace = true
