[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-lighting-ltc"
version = "0.1.0"

[dependencies]
rendiation-algebra = { path = "../../../math/algebra" }
rendiation-shader-api = { path = "../../../shader/api" }
rendiation-texture-core = { path = "../../texture/core" }
rendiation-lighting-gpu-system = { path = "../gpu-system/lighting-system" }
rendiation-lighting-transport = { path = "../transport" }

[dev-dependencies]
half = { version = "*", features = ["bytemuck"] }
bytemuck = { workspace = true, features = ["derive"] }

[lints]
workspace = true
