[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-texture-gpu-base"
version = "0.1.0"

[dependencies]
rendiation-algebra = { path = "../../../math/algebra" }
rendiation-texture-core = { path = "../core" }
rendiation-shader-api = { path = "../../../shader/api" }
rendiation-webgpu = { path = "../../../platform/graphics/webgpu" }
rendiation-fast-down-sampling-2d = { path = "../../../shader/fast-down-sampling-2d" }

[lints]
workspace = true
