[package]
authors = ["mikialex <miikiialexx@gmail.com>"]
edition = "2021"
name = "rendiation-mesh-segmentation"
version = "0.1.0"

[dependencies]
rendiation-algebra = { path = "../../../math/algebra" }
rendiation-geometry = { path = "../../../math/geometry" }
rendiation-mesh-core = { path = "../core" }
rendiation-space-algorithm = { path = "../../space" }

[dev-dependencies]
rendiation-mesh-test-util = { path = "../test-util" }

[lints]
workspace = true
