[package]
authors = ["mikialex <miikiialexx@gmail.com>"]
edition = "2021"
name = "rendiation-scene-obj-loader"
version = "0.1.0"

[dependencies]
image = { workspace = true }
database = { path = "../../../../utility/database" }
rendiation-algebra = { path = "../../../../math/algebra" }
rendiation-mesh-core = { path = "../../../../content/mesh/core" }
rendiation-scene-core = { path = "../../../core" }
rendiation-texture-loader = { path = "../../../../content/texture/loader" }
smallvec = { workspace = true }
thiserror = "1.0.43"
tobj = "4.0.0"

[lints]
workspace = true
