use crate::*;

// The vector component selection, swizzle and the component references. The named methods
// (`.x()`, `.zyx()`, `.bgra()`, ...) of the vector value and the vector pointers are generated by
// `impl_shader_swizzles` and implemented by the component index based methods here.

const fn assert_swizzle_component(component: u8, size: u8) {
  assert!(
    component < size,
    "the swizzle component is out of the vector size"
  );
}

/// check the first `len` components of the writable swizzle view
const fn assert_swizzle_view_components(size: u8, len: usize, a: u8, b: u8, c: u8, d: u8) {
  let components = [a, b, c, d];
  let mut i = 0;
  while i < len {
    assert!(
      components[i] < size,
      "the swizzle component is out of the vector size"
    );
    let mut j = i + 1;
    while j < len {
      assert!(
        components[i] != components[j],
        "the components of a writable swizzle view must be distinct"
      );
      j += 1;
    }
    i += 1;
  }
}

fn swizzle_raw(source: ShaderNodeRawHandle, components: &[u8]) -> ShaderNodeRawHandle {
  let size = match components.len() {
    2 => VectorSize::Bi,
    3 => VectorSize::Tri,
    4 => VectorSize::Quad,
    _ => unreachable!("invalid swizzle size"),
  };
  let mut pattern = [0; 4];
  pattern[..components.len()].copy_from_slice(components);
  ShaderNodeExpr::Swizzle {
    source,
    size,
    pattern,
  }
  .insert_api_raw()
}

/// The component selection and swizzle by the component indices, the out of range index is a
/// compile error.
impl<V: ShaderVec> Node<V> {
  /// `v.component::<2>()` is `v.z`
  #[inline(always)]
  pub fn component<const I: u8>(&self) -> Node<V::Item> {
    const { assert_swizzle_component(I, V::SIZE) };
    unsafe { index_access_field(self.handle(), I as usize).into_node() }
  }

  /// `v.swizzle2::<1, 0>()` is `v.yx`
  #[inline(always)]
  pub fn swizzle2<const A: u8, const B: u8>(&self) -> Node<Vec2<V::Item>> {
    const { assert_swizzle_component(A, V::SIZE) };
    const { assert_swizzle_component(B, V::SIZE) };
    unsafe { swizzle_raw(self.handle(), &[A, B]).into_node() }
  }

  /// `v.swizzle3::<2, 1, 0>()` is `v.zyx`
  #[inline(always)]
  pub fn swizzle3<const A: u8, const B: u8, const C: u8>(&self) -> Node<Vec3<V::Item>> {
    const { assert_swizzle_component(A, V::SIZE) };
    const { assert_swizzle_component(B, V::SIZE) };
    const { assert_swizzle_component(C, V::SIZE) };
    unsafe { swizzle_raw(self.handle(), &[A, B, C]).into_node() }
  }

  /// `v.swizzle4::<3, 2, 1, 0>()` is `v.wzyx`
  #[inline(always)]
  pub fn swizzle4<const A: u8, const B: u8, const C: u8, const D: u8>(
    &self,
  ) -> Node<Vec4<V::Item>> {
    const { assert_swizzle_component(A, V::SIZE) };
    const { assert_swizzle_component(B, V::SIZE) };
    const { assert_swizzle_component(C, V::SIZE) };
    const { assert_swizzle_component(D, V::SIZE) };
    unsafe { swizzle_raw(self.handle(), &[A, B, C, D]).into_node() }
  }
}

/// The component references of the vector pointer, `v.component::<2>().store(..)` is `v.z = ..`.
impl<V: ShaderVec> DirectPrimitivePtrView<V> {
  #[inline(always)]
  pub fn component<const I: u8>(&self) -> ShaderPtrOf<V::Item> {
    const { assert_swizzle_component(I, V::SIZE) };
    V::Item::create_view_from_raw_ptr(self.raw().field_index(I as usize))
  }

  /// the reference to the component selected by the runtime index, `v[i]`
  #[inline(always)]
  pub fn index(&self, index: impl Into<Node<u32>>) -> ShaderPtrOf<V::Item> {
    V::Item::create_view_from_raw_ptr(self.raw().field_array_index(index.into()))
  }

  /// the writable swizzle view `v.yx`, the components must be distinct
  #[inline(always)]
  pub fn swizzle2<const A: u8, const B: u8>(&self) -> VectorSwizzlePtrView<V, Vec2<V::Item>> {
    const { assert_swizzle_view_components(V::SIZE, 2, A, B, 0, 0) };
    VectorSwizzlePtrView::new(self.raw().clone(), [A, B, 0, 0])
  }

  /// the writable swizzle view `v.zyx`, the components must be distinct
  #[inline(always)]
  pub fn swizzle3<const A: u8, const B: u8, const C: u8>(
    &self,
  ) -> VectorSwizzlePtrView<V, Vec3<V::Item>> {
    const { assert_swizzle_view_components(V::SIZE, 3, A, B, C, 0) };
    VectorSwizzlePtrView::new(self.raw().clone(), [A, B, C, 0])
  }

  /// the writable swizzle view `v.wzyx`, the components must be distinct
  #[inline(always)]
  pub fn swizzle4<const A: u8, const B: u8, const C: u8, const D: u8>(
    &self,
  ) -> VectorSwizzlePtrView<V, Vec4<V::Item>> {
    const { assert_swizzle_view_components(V::SIZE, 4, A, B, C, D) };
    VectorSwizzlePtrView::new(self.raw().clone(), [A, B, C, D])
  }
}

/// The component references of the readonly vector pointer.
impl<V: ShaderVec> ReadonlyDirectPrimitivePtrView<V> {
  #[inline(always)]
  pub fn component<const I: u8>(&self) -> ShaderReadonlyPtrOf<V::Item> {
    const { assert_swizzle_component(I, V::SIZE) };
    V::Item::create_readonly_view_from_raw_ptr(self.raw().field_index(I as usize))
  }

  /// the reference to the component selected by the runtime index, `v[i]`
  #[inline(always)]
  pub fn index(&self, index: impl Into<Node<u32>>) -> ShaderReadonlyPtrOf<V::Item> {
    V::Item::create_readonly_view_from_raw_ptr(self.raw().field_array_index(index.into()))
  }
}

/// The WGSL swizzle view of a writable vector reference (the `swizzle_assignment` language
/// extension), for example `v.yz = value` is `v.yz().store(value)`. The components are distinct.
///
/// Like WGSL, both the read and the write access the entire vector in memory, so concurrently
/// writing the different components of the same vector in shared memory is a data race.
pub struct VectorSwizzlePtrView<V, O> {
  phantom: PhantomData<(V, O)>,
  vector: BoxedShaderPtr,
  components: [u8; 4],
}

impl<V, O> Clone for VectorSwizzlePtrView<V, O> {
  fn clone(&self) -> Self {
    Self {
      phantom: PhantomData,
      vector: self.vector.clone(),
      components: self.components,
    }
  }
}

impl<V: ShaderVec, O: ShaderVec<Item = V::Item>> VectorSwizzlePtrView<V, O> {
  fn new(vector: BoxedShaderPtr, components: [u8; 4]) -> Self {
    Self {
      phantom: PhantomData,
      vector,
      components,
    }
  }

  /// read the entire vector and select the components
  #[inline(always)]
  pub fn load(&self) -> Node<O> {
    let components = &self.components[..O::SIZE as usize];
    unsafe { swizzle_raw(self.vector.load(), components).into_node() }
  }

  /// read the entire vector, replace the selected components and write the entire vector back
  #[inline(always)]
  pub fn store(&self, value: impl Into<Node<O>>) {
    swizzle_view_store(
      &self.vector,
      V::primitive_ty(),
      V::SIZE,
      &self.components[..O::SIZE as usize],
      value.into().handle(),
    )
  }
}

fn swizzle_view_store(
  vector: &BoxedShaderPtr,
  vector_ty: PrimitiveShaderValueType,
  size: u8,
  components: &[u8],
  value: ShaderNodeRawHandle,
) {
  // the view covers all the components, so the old value is not required
  let old = (components.len() < size as usize).then(|| vector.load());
  let parameters = (0..size)
    .map(|i| unsafe {
      match components.iter().position(|c| *c == i) {
        Some(j) => index_access_field(value, j),
        None => index_access_field(old.unwrap(), i as usize),
      }
    })
    .collect();
  let new = ShaderNodeExpr::Compose {
    target: ShaderSizedValueType::Primitive(vector_ty),
    parameters,
  }
  .insert_api_raw();
  vector.store(new);
}

impl_shader_swizzles!();

macro_rules! matrix_columns {
  ($Mat: ident, $Column: ident, { $($name: ident: $index: expr),+ }) => {
    impl<T: ShaderFloatType> Node<$Mat<T>> {
      $(
        #[inline(always)]
        pub fn $name(&self) -> Node<$Column<T>> {
          unsafe { index_access_field(self.handle(), $index).into_node() }
        }
      )+
    }

    /// The column references of the matrix pointer.
    impl<T: ShaderFloatType> DirectPrimitivePtrView<$Mat<T>> {
      $(
        #[inline(always)]
        pub fn $name(&self) -> ShaderPtrOf<$Column<T>> {
          $Column::<T>::create_view_from_raw_ptr(self.raw().field_index($index))
        }
      )+

      /// the reference to the column selected by the runtime index, `m[i]`
      #[inline(always)]
      pub fn index(&self, index: impl Into<Node<u32>>) -> ShaderPtrOf<$Column<T>> {
        $Column::<T>::create_view_from_raw_ptr(self.raw().field_array_index(index.into()))
      }
    }

    /// The column references of the readonly matrix pointer.
    impl<T: ShaderFloatType> ReadonlyDirectPrimitivePtrView<$Mat<T>> {
      $(
        #[inline(always)]
        pub fn $name(&self) -> ShaderReadonlyPtrOf<$Column<T>> {
          $Column::<T>::create_readonly_view_from_raw_ptr(self.raw().field_index($index))
        }
      )+

      /// the reference to the column selected by the runtime index, `m[i]`
      #[inline(always)]
      pub fn index(&self, index: impl Into<Node<u32>>) -> ShaderReadonlyPtrOf<$Column<T>> {
        $Column::<T>::create_readonly_view_from_raw_ptr(self.raw().field_array_index(index.into()))
      }
    }
  };
}

matrix_columns!(Mat2, Vec2, { x: 0, y: 1 });
matrix_columns!(Mat3, Vec3, { x: 0, y: 1, z: 2 });
matrix_columns!(Mat4, Vec4, { x: 0, y: 1, z: 2, w: 3 });
matrix_columns!(Mat2x3, Vec3, { x: 0, y: 1 });
matrix_columns!(Mat2x4, Vec4, { x: 0, y: 1 });
matrix_columns!(Mat3x2, Vec2, { x: 0, y: 1, z: 2 });
matrix_columns!(Mat3x4, Vec4, { x: 0, y: 1, z: 2 });
matrix_columns!(Mat4x2, Vec2, { x: 0, y: 1, z: 2, w: 3 });
matrix_columns!(Mat4x3, Vec3, { x: 0, y: 1, z: 2, w: 3 });
