[package]
authors = ["MikiAlex <miikiialexx@gmail.com>"]
edition = "2021"
name = "rendiation-platform-event-input"
version = "0.1.0"

[dependencies]
winit = { workspace = true }
fast-hash-collection = { path = "../../utility/fast-hash-collection" }
log = { workspace = true }

[target.'cfg(target_family = "wasm")'.dependencies]
web-time = { workspace = true }


[lints]
workspace = true
