[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-mesh-simplification"
version = "0.1.0"

[dependencies]
rendiation-algebra = { path = "../../../math/algebra" }
rendiation-geometry = { path = "../../../math/geometry" }
rendiation-mesh-core = { path = "../core" }

[dev-dependencies]
rendiation-mesh-test-util = { path = "../test-util" }

[lints]
workspace = true
