[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-space-algorithm"
version = "0.1.0"

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
harness = false
name = "bvh"

[dependencies]

rendiation-abstract-tree = { path = "../../utility/abstract-tree" }
rendiation-algebra = { path = "../../math/algebra" }
rendiation-geometry = { path = "../../math/geometry" }

log = { workspace = true }
rand = { workspace = true }

[lints]
workspace = true
