[package]
authors = ["mikialex <miikiialexx@gmail.com>"]
edition = "2021"
name = "rendiation-gizmo"
version = "0.1.0"

[dependencies]
rendiation-algebra = { path = "../../math/algebra" }
rendiation-geometry = { path = "../../math/geometry" }
rendiation-scene-core = { path = "../../scene/core" }
rendiation-gui-3d = { path = "../gui-3d" }
rendiation-mesh-generator = { path = "../../content/mesh/generator" }

[lints]
workspace = true
