# see https://github.com/mozilla/cbindgen/blob/main/template.toml
# and https://github.com/mozilla/cbindgen/blob/main/docs.md#cbindgentoml

language = "C"

[parse]
parse_deps = true
include = ["rendiation-mesh-core"]
