# see https://github.com/mozilla/cbindgen/blob/main/template.toml
# and https://github.com/mozilla/cbindgen/blob/main/docs.md#cbindgentoml

language = "C"

include_guard = "RENDIATION_C_HEADER"

[parse]
parse_deps = true
include = [
    "rendiation-mesh-core",
    "rendiation-occ-style-draw-control",
    "rendiation-occ-style-material",
    "rendiation-text-3d",
    "rendiation-texture-gpu-process",
]
