
[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-texture-as-buffer"
version = "0.1.0"

[dependencies]
rendiation-shader-api = { path = "../../../shader/api" }
rendiation-webgpu = { path = "../webgpu" }
fast-hash-collection = { path = "../../../utility/fast-hash-collection" }
parking_lot = { workspace = true }
dyn-clone = { workspace = true }

[lints]
workspace = true
