[package]
authors = ["MikiAlex <miikiialexx@gmail.com>"]
edition = "2024"
name = "rendiation-webgpu-texture-as-buffer"
version = "0.1.0"

[dependencies]
rendiation-shader-api = { path = "../../../shader/api" }
rendiation-webgpu = { path = "../webgpu" }
parking_lot = { workspace = true }

[dev-dependencies]
rendiation-webgpu-virtual-typed-combine-buffer = { path = "../webgpu-virtual-typed-combine-buffer" }
pollster = { workspace = true }

[lints]
workspace = true
